### ISSUE TITLE
 error while loading the extension

### ISSUE THREAD

**Issue by Mohamed-G2021** [AhmedElTabarani/hadith-checker-extension#1]
بعد اختيار load extension وتحديد الملف الذي تم فك ضغطه
تظهر لي رسالة الخطأ هذه 

Manifest file is missing or unreadable
Could not load manifest.

**Comment by AhmedElTabarani** [comment]
تم رفع الإضافة على المتجر، لا يوجد هناك داعي لتحميله يدويًا 

رابط الإضافة:
https://chrome.google.com/webstore/detail/hadith-checker/cfbllcckohbiiplkigbfllfphhakanke

**Comment by AhmedElTabarani** [comment]
@Mohamed-G2021 
اشتغل معاك ؟

**Comment by Mohamed-G2021** [comment]
> @Mohamed-G2021 اشتغل معاك ؟
نزلته من المتجر واشتغل الحمد لله
جزاك الله خيرا

**Comment by Mohamed-G2021** [comment]
تم حل المشكلة برفع الإضافة على المتحر
