### ISSUE TITLE
وضع زر لعرض تفسير الحديث (للبخاري ومسلم)

### ISSUE THREAD

**Issue by AhmedElTabarani** [AhmedElTabarani/hadith-checker-extension#20]

**Comment by AhmedElTabarani** [comment]
موقع الدرر به تفسيرات لكن ليس هناك API لها

**Comment by proXDhiya** [comment]
هل من الممكن مشاركة رابط الموقع "الدرر" لبحث عن وسيلة لاستخراج التفسيرات و المساهمة في المشروع

**Comment by AhmedElTabarani** [comment]
https://www.dorar.net/

الموقع لا يوفر API واضح للتفاسير
حالا أنا عملت سكريبت لسحب كل تفاسير الأحاديث بشكل تلقائي
ونجحت أنني أحصل على اكثر من 132 ألف حديث بتفسيره
تبقى فقط أن أقوم بعمل API له

**Comment by AhmedElTabarani** [comment]
> هل من الممكن مشاركة رابط الموقع "الدرر" لبحث عن وسيلة لاستخراج التفسيرات و المساهمة في المشروع

حابب اعلن انني نجحت الحمد لله في عمل  API لسحب  الأحاديث مع الشرح  وسيتم ربطها في الإضافة الإصدار  v1.2 إن شاء لله
https://github.com/AhmedElTabarani/dorar-hadith-api

**Comment by AhmedElTabarani** [comment]
FIX #24
