### ISSUE TITLE
English Please

### ISSUE THREAD

**Issue by blueray453** [AhmedElTabarani/hadith-checker-extension#31]
Assalmualaikum Brother,

Can We get English Translation.

Jazak Allah

**Comment by AhmedElTabarani** [comment]
Waealaykum alsalam Brother

I was looking for a reliable source for translated hadiths for a while, but I did not find anything
Whether it's a website I can pull data from or an API I can use

But how will it be used?
- Will the user search for a translation of an Arabic hadith he has selected?
- Will the user search using a hadith translated into English?

I do not think that there is uniformity of translation, so the second choice is not a flexible option

The first option is possible, but I rely on the [Al Dorar Al Saniyyah](https://dorar.net/) website as the primary source
Unfortunately, he does not have a translation of the hadiths
Rather, all he has is an incomplete translation of some of Bukhari’s hadiths
https://dorar.net/en/ahadith

I think I'll do another round of research to see what's new or what I can use

**Comment by blueray453** [comment]
Assalmualaikum Brother, Jazak Allah for looking into this.

**Comment by AhmedElTabarani** [comment]
@blueray453 I want to tell you that I found a good site and I manage to scrapping its data
https://github.com/AhmedElTabarani/sunnah-hadith-api

So, I will add the search in English to the Extension soon

The wonderful thing is that the site allows you to search using Arabic or English text and the results are both Arabic and English

You were the reason that made me research and work hard on it, so thank you very much

**Comment by blueray453** [comment]
Assalmualaikum Brother, Jazak Allah Khair Brother.

**Comment by AhmedElTabarani** [comment]
@blueray453 take a look here https://github.com/AhmedElTabarani/hadith-checker-extension/releases/tag/v1.6
