### ISSUE TITLE
مشاركة نتائج البحث

### ISSUE THREAD

**Issue by AhmedElTabarani** [AhmedElTabarani/hadith-checker-extension#5]
محاولة إنشاء زر لمشاركة حديث ما من نتائج البحث
سواء مشاركة كصورة أو كرابط لموقع الدرر السنية أو كنص

- [x] مشاركة رابط لموقع الدرر السنية
- [x] مشاركة كنص
- [x] مشاركة كصورة

**Comment by adelpro** [comment]
السلام عليكم
من أجل نشر نتائج البحث كصورة، يمكنك تجربة هذا الحل المقترح على موقع stackoverflow
https://stackoverflow.com/a/75133072/15106651
